version: '3'

# usage: task judge
tasks:
  judge:
    cmds:
      - podman machine start
      - podman compose up -d

  podman:
    cmds:
      - podman machine start

  shutdown:
    - podman machine stop
    # - wsl --shutdown
  
  pods:
    cmds:
      - podman ps

  pstop:
    cmds:
      - podman stop --all
    