version: '3'

# usage: task judge
tasks:
  judge:
    cmds:
      - podman machine start
      # - docker-compose up -d db redis
      - sleep 10s
      - podman compose up -d
      - sleep 5s

  podman:
    cmds:
      - podman machine start

  shutdown:
    - podman machine stop
    # - wsl --shutdown
  
  pods:
    cmds:
      - podman ps

  pstop:
    cmds:
      - podman stop --all
    
  frontend:
    cmds:
      - npm run dev